name: Build and release
on: push
jobs:
  # minimal:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: nixbuild/nix-quick-install-action@v5
  #     - run: nix-build --version


  flakes-simple:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v24
        with:
          nix_version: "2.16.1"
          # nix_conf: features = nix-command
      - uses: cachix/cachix-action@v10
        with:
          name: anka-213
          # # If you chose signing key for write access
          # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      # - uses: haskell/actions/setup@v1
      #   with:
      #     ghc-version: '8.8.4' # Exact version of ghc to use
      #     # cabal-version: 'latest'. Omitted, but defaults to 'latest'
      #     enable-stack: true
      #     stack-version: '2.7.1'
      # - name: nix-build --dry-run
      #   run: nix build -L -f . exe --dry-run
      - run: nix build --version
      - name: nix-build
        run: nix build -L -f . exe --extra-experimental-features nix-command
        # Don't build the non-static version on macos
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Build redistributable for MacOS
        run: nix build -L -f . gf-lsp-redistributable --extra-experimental-features nix-command -o result-redistributable
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Make bundle for linux
        run: nix bundle -f . exe --extra-experimental-features 'nix-command flakes' -o result-lsp-bundle
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - uses: actions/upload-artifact@v2
        with:
          name: gf-lsp-${{ matrix.os }}
            # result/bin/gf-lsp
          path: |
            result-redistributable/bin/gf-lsp
            result-lsp-bundle

  make-release:
    runs-on: ubuntu-latest
    needs: flakes-simple
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
      - run: ls -lR
      # TODO make a tarball
      - run: |
          mv gf-lsp-macos-latest/result-redistributable/bin/gf-lsp gf-lsp-macos-intel
          mv gf-lsp-ubuntu-latest/result-lsp-bundle gf-lsp-linux-bundle

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          tag_name: prerelease
          draft: true
          name: Experiment with using releases
          body: |
            If you're running linux or an intel mac you can:
              - Download the `gf-lsp-linux-bundle` or `gf-lsp-macos-intel` respectively
              - Rename it to `gf-lsp`
              - make it executable using `chmod +x gf-lsp`
              - and put it in one of the directories in your `$PATH`

              after that reload your editor to make the lsp extension find the executable
          files: |
            gf-lsp-macos-intel
            gf-lsp-linux-bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_REPOSITORY: ${{ GITHUB_REPOSITORY }}
